# Anna KaRNNa

In this notebook, I'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [86]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [87]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = set(text)
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [88]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [89]:
encoded[:100]

array([38, 76, 59,  3, 17, 31, 67, 16, 66, 53, 53, 53, 77, 59,  3,  3, 23,
       16, 24, 59, 18, 26, 63, 26, 31, 64, 16, 59, 67, 31, 16, 59, 63, 63,
       16, 59, 63, 26, 57, 31, 10, 16, 31, 36, 31, 67, 23, 16, 65, 81, 76,
       59,  3,  3, 23, 16, 24, 59, 18, 26, 63, 23, 16, 26, 64, 16, 65, 81,
       76, 59,  3,  3, 23, 16, 26, 81, 16, 26, 17, 64, 16, 14, 62, 81, 53,
       62, 59, 23, 30, 53, 53, 39, 36, 31, 67, 23, 17, 76, 26, 81], dtype=int32)

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [90]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

In [91]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the batch size and number of batches we can make
    batch_size = n_seqs * n_steps
    n_batches = len(arr)//batch_size
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * batch_size]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [92]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [93]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[38 76 59  3 17 31 67 16 66 53]
 [16 59 18 16 81 14 17 16 28 14]
 [36 26 81 30 53 53 43  4 31 64]
 [81 16 58 65 67 26 81 28 16 76]
 [16 26 17 16 26 64 35 16 64 26]
 [16  6 17 16 62 59 64 53 14 81]
 [76 31 81 16 13 14 18 31 16 24]
 [10 16 22 65 17 16 81 14 62 16]
 [17 16 26 64 81 19 17 30 16 29]
 [16 64 59 26 58 16 17 14 16 76]]

y
 [[76 59  3 17 31 67 16 66 53 53]
 [59 18 16 81 14 17 16 28 14 26]
 [26 81 30 53 53 43  4 31 64 35]
 [16 58 65 67 26 81 28 16 76 26]
 [26 17 16 26 64 35 16 64 26 67]
 [ 6 17 16 62 59 64 53 14 81 63]
 [31 81 16 13 14 18 31 16 24 14]
 [16 22 65 17 16 81 14 62 16 64]
 [16 26 64 81 19 17 30 16 29 76]
 [64 59 26 58 16 17 14 16 76 31]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`.

In [94]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. For example,

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow will create different weight matrices for all `cell` objects. Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [95]:
def lstm_cell(lstm_size,keep_prod):
    cell = tf.contrib.rnn.NASCell(lstm_size, reuse=tf.get_variable_scope().reuse)
    return tf.contrib.rnn.DropoutWrapper(cell, output_keep_prob=keep_prod)


In [96]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    # Use a basic LSTM cell
    #lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
    
    # Add dropout to the cell
    #drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    # Stack up multiple LSTM layers, for deep learning
    # cell = tf.contrib.rnn.MultiRNNCell([drop] * num_layers)
    # MultiRNNCell([BasicLSTMCell(...) for _ in range(num_layers)])
    rnn_cells = tf.contrib.rnn.MultiRNNCell([lstm_cell(lstm_size,keep_prob) for _ in range(num_layers)], state_is_tuple = True)

    initial_state = rnn_cells.zero_state(batch_size, tf.float32)
    
    return rnn_cells, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$.

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

In [97]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        x: Input tensor
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # That is, the shape should be batch_size*num_steps rows by lstm_size columns
    seq_output = tf.concat(lstm_output, axis=1)
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

In [98]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per batch_size per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [99]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

In [100]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN and collect the outputs
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here I'm defining the hyperparameters for the network. 

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.


In [101]:
batch_size = 100        # Sequences per batch
num_steps = 100         # Number of sequence steps per batch
lstm_size = 512         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.001   # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

In [121]:
epochs = 4
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/4...  Training Step: 1...  Training loss: 4.4189...  6.1058 sec/batch
Epoch: 1/4...  Training Step: 2...  Training loss: 4.4162...  6.1373 sec/batch
Epoch: 1/4...  Training Step: 3...  Training loss: 4.4133...  6.5628 sec/batch
Epoch: 1/4...  Training Step: 4...  Training loss: 4.4100...  8.3439 sec/batch
Epoch: 1/4...  Training Step: 5...  Training loss: 4.4059...  7.4316 sec/batch
Epoch: 1/4...  Training Step: 6...  Training loss: 4.4006...  9.3314 sec/batch
Epoch: 1/4...  Training Step: 7...  Training loss: 4.3936...  6.3849 sec/batch
Epoch: 1/4...  Training Step: 8...  Training loss: 4.3838...  6.4868 sec/batch
Epoch: 1/4...  Training Step: 9...  Training loss: 4.3693...  6.7828 sec/batch
Epoch: 1/4...  Training Step: 10...  Training loss: 4.3482...  6.5327 sec/batch
Epoch: 1/4...  Training Step: 11...  Training loss: 4.3117...  6.5971 sec/batch
Epoch: 1/4...  Training Step: 12...  Training loss: 4.2422...  6.7471 sec/batch
Epoch: 1/4...  Training Step: 13...  Training los

Epoch: 1/4...  Training Step: 104...  Training loss: 3.1377...  7.2089 sec/batch
Epoch: 1/4...  Training Step: 105...  Training loss: 3.1366...  7.0977 sec/batch
Epoch: 1/4...  Training Step: 106...  Training loss: 3.1398...  7.1961 sec/batch
Epoch: 1/4...  Training Step: 107...  Training loss: 3.1165...  7.2120 sec/batch
Epoch: 1/4...  Training Step: 108...  Training loss: 3.1220...  7.1681 sec/batch
Epoch: 1/4...  Training Step: 109...  Training loss: 3.1348...  7.1007 sec/batch
Epoch: 1/4...  Training Step: 110...  Training loss: 3.1110...  7.1311 sec/batch
Epoch: 1/4...  Training Step: 111...  Training loss: 3.1337...  7.3768 sec/batch
Epoch: 1/4...  Training Step: 112...  Training loss: 3.1372...  7.2220 sec/batch
Epoch: 1/4...  Training Step: 113...  Training loss: 3.1287...  7.3630 sec/batch
Epoch: 1/4...  Training Step: 114...  Training loss: 3.1169...  7.1460 sec/batch
Epoch: 1/4...  Training Step: 115...  Training loss: 3.1154...  7.1898 sec/batch
Epoch: 1/4...  Training Step

Epoch: 2/4...  Training Step: 206...  Training loss: 3.0040...  6.8592 sec/batch
Epoch: 2/4...  Training Step: 207...  Training loss: 2.9898...  6.9895 sec/batch
Epoch: 2/4...  Training Step: 208...  Training loss: 2.9790...  6.9576 sec/batch
Epoch: 2/4...  Training Step: 209...  Training loss: 2.9613...  6.8784 sec/batch
Epoch: 2/4...  Training Step: 210...  Training loss: 2.9732...  6.9768 sec/batch
Epoch: 2/4...  Training Step: 211...  Training loss: 2.9580...  6.8864 sec/batch
Epoch: 2/4...  Training Step: 212...  Training loss: 2.9782...  7.1245 sec/batch
Epoch: 2/4...  Training Step: 213...  Training loss: 2.9640...  6.9064 sec/batch
Epoch: 2/4...  Training Step: 214...  Training loss: 2.9532...  6.9096 sec/batch
Epoch: 2/4...  Training Step: 215...  Training loss: 2.9359...  6.9348 sec/batch
Epoch: 2/4...  Training Step: 216...  Training loss: 2.9717...  6.9850 sec/batch
Epoch: 2/4...  Training Step: 217...  Training loss: 2.9377...  6.9262 sec/batch
Epoch: 2/4...  Training Step

Epoch: 2/4...  Training Step: 307...  Training loss: 2.3756...  7.4236 sec/batch
Epoch: 2/4...  Training Step: 308...  Training loss: 2.3240...  7.5972 sec/batch
Epoch: 2/4...  Training Step: 309...  Training loss: 2.3539...  8.9797 sec/batch
Epoch: 2/4...  Training Step: 310...  Training loss: 2.3599...  9.8445 sec/batch
Epoch: 2/4...  Training Step: 311...  Training loss: 2.3442...  7.9021 sec/batch
Epoch: 2/4...  Training Step: 312...  Training loss: 2.3370...  7.2273 sec/batch
Epoch: 2/4...  Training Step: 313...  Training loss: 2.3239...  7.1091 sec/batch
Epoch: 2/4...  Training Step: 314...  Training loss: 2.3000...  7.2220 sec/batch
Epoch: 2/4...  Training Step: 315...  Training loss: 2.3244...  7.1129 sec/batch
Epoch: 2/4...  Training Step: 316...  Training loss: 2.3292...  7.2235 sec/batch
Epoch: 2/4...  Training Step: 317...  Training loss: 2.3473...  7.1202 sec/batch
Epoch: 2/4...  Training Step: 318...  Training loss: 2.3179...  7.1345 sec/batch
Epoch: 2/4...  Training Step

Epoch: 3/4...  Training Step: 408...  Training loss: 2.0628...  12.0554 sec/batch
Epoch: 3/4...  Training Step: 409...  Training loss: 2.0896...  11.3285 sec/batch
Epoch: 3/4...  Training Step: 410...  Training loss: 2.1156...  12.4940 sec/batch
Epoch: 3/4...  Training Step: 411...  Training loss: 2.0760...  12.3983 sec/batch
Epoch: 3/4...  Training Step: 412...  Training loss: 2.0545...  12.4009 sec/batch
Epoch: 3/4...  Training Step: 413...  Training loss: 2.0717...  12.8306 sec/batch
Epoch: 3/4...  Training Step: 414...  Training loss: 2.1108...  11.0202 sec/batch
Epoch: 3/4...  Training Step: 415...  Training loss: 2.0656...  13.3982 sec/batch
Epoch: 3/4...  Training Step: 416...  Training loss: 2.0594...  11.9073 sec/batch
Epoch: 3/4...  Training Step: 417...  Training loss: 2.0591...  12.2876 sec/batch
Epoch: 3/4...  Training Step: 418...  Training loss: 2.1066...  12.7825 sec/batch
Epoch: 3/4...  Training Step: 419...  Training loss: 2.0560...  13.6131 sec/batch
Epoch: 3/4...  T

Epoch: 3/4...  Training Step: 508...  Training loss: 1.9151...  11.7955 sec/batch
Epoch: 3/4...  Training Step: 509...  Training loss: 1.9099...  12.4146 sec/batch
Epoch: 3/4...  Training Step: 510...  Training loss: 1.9148...  12.7034 sec/batch
Epoch: 3/4...  Training Step: 511...  Training loss: 1.8989...  11.3591 sec/batch
Epoch: 3/4...  Training Step: 512...  Training loss: 1.8774...  12.5712 sec/batch
Epoch: 3/4...  Training Step: 513...  Training loss: 1.9049...  13.2176 sec/batch
Epoch: 3/4...  Training Step: 514...  Training loss: 1.9141...  12.4629 sec/batch
Epoch: 3/4...  Training Step: 515...  Training loss: 1.9143...  11.0788 sec/batch
Epoch: 3/4...  Training Step: 516...  Training loss: 1.9109...  14.0881 sec/batch
Epoch: 3/4...  Training Step: 517...  Training loss: 1.9296...  12.6191 sec/batch
Epoch: 3/4...  Training Step: 518...  Training loss: 1.8883...  12.2609 sec/batch
Epoch: 3/4...  Training Step: 519...  Training loss: 1.8933...  12.8592 sec/batch
Epoch: 3/4...  T

Epoch: 4/4...  Training Step: 608...  Training loss: 1.8524...  12.6961 sec/batch
Epoch: 4/4...  Training Step: 609...  Training loss: 1.8102...  13.4540 sec/batch
Epoch: 4/4...  Training Step: 610...  Training loss: 1.7852...  11.0828 sec/batch
Epoch: 4/4...  Training Step: 611...  Training loss: 1.8051...  13.3713 sec/batch
Epoch: 4/4...  Training Step: 612...  Training loss: 1.8437...  11.9229 sec/batch
Epoch: 4/4...  Training Step: 613...  Training loss: 1.8076...  12.8634 sec/batch
Epoch: 4/4...  Training Step: 614...  Training loss: 1.8053...  12.7259 sec/batch
Epoch: 4/4...  Training Step: 615...  Training loss: 1.7882...  12.7162 sec/batch
Epoch: 4/4...  Training Step: 616...  Training loss: 1.8496...  12.9006 sec/batch
Epoch: 4/4...  Training Step: 617...  Training loss: 1.7998...  12.6468 sec/batch
Epoch: 4/4...  Training Step: 618...  Training loss: 1.8079...  11.9756 sec/batch
Epoch: 4/4...  Training Step: 619...  Training loss: 1.7962...  13.3679 sec/batch
Epoch: 4/4...  T

Epoch: 4/4...  Training Step: 709...  Training loss: 1.7165...  7.0099 sec/batch
Epoch: 4/4...  Training Step: 710...  Training loss: 1.6868...  6.7949 sec/batch
Epoch: 4/4...  Training Step: 711...  Training loss: 1.7192...  6.8698 sec/batch
Epoch: 4/4...  Training Step: 712...  Training loss: 1.7268...  6.8482 sec/batch
Epoch: 4/4...  Training Step: 713...  Training loss: 1.7313...  6.7932 sec/batch
Epoch: 4/4...  Training Step: 714...  Training loss: 1.7158...  6.9176 sec/batch
Epoch: 4/4...  Training Step: 715...  Training loss: 1.7385...  6.9276 sec/batch
Epoch: 4/4...  Training Step: 716...  Training loss: 1.7012...  6.7915 sec/batch
Epoch: 4/4...  Training Step: 717...  Training loss: 1.7013...  7.0843 sec/batch
Epoch: 4/4...  Training Step: 718...  Training loss: 1.7290...  6.9812 sec/batch
Epoch: 4/4...  Training Step: 719...  Training loss: 1.7237...  6.9049 sec/batch
Epoch: 4/4...  Training Step: 720...  Training loss: 1.6865...  6.9505 sec/batch
Epoch: 4/4...  Training Step

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [122]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints/i792_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i792_l512.ckpt"

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [123]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [124]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [125]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints/i792_l512.ckpt'

In [126]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i792_l512.ckpt
Far had the comploon, and the send himself, and how have himself the same of his stalt in anster
sumpant the coulden hand, that she shate to be her told her as the momant."

"Well, and
sation that and said that the
pistrown....
 he despend to the chook and
her head.

"Yes, and he he had nather a dright with his was to at home anywing of the pisition."

And a colling it the
bord,
who calling a dropiting the man the stret was thought with," that he said a secour and word over the
recretty
was he say and as
that an ond of all whething to
the contalle and she could not have all the stranger," said he had not to some one was her, and whisken him in her has been. The said
and at the pertating his followed had bones, what was thing, and stelle that so me a mee to
do some to
said,
three was stain, with a
little but, and which a more husband was a man in
a so triev. The decient the beging had
have at his hand and all
she was t

In [127]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i200_l512.ckpt
Far  tt e  haeess aaeetsesn tae h  htte t tth  hoe eeee  htei  tthe e tottatthett t aa eo eatttat htan aenne het aa hee  teon htaeten tatt  teane aat  otoasen h ae teoest aonn  heessa aaen ha  eeet  ae ha the t thet aaees et aenss  ttoeons teaee aet theen  aenne ae  eaese hota ha tae tooese a eat hten a ho  th toe  otet  eonsee h henset hati thaieet  teon  o e tateetaiest  h  oo tho to  eo eeset tee eo hei  atan  oh a ae  he hoansnt het a h e  oon  hetin h eos  eteee t oen h henesssene heseee  e a  ohest aetaet haetn  he eoe aan e  h thatt atettaitan he toe  ao eth  htee aae  he ha e aoe  a ho  o eate h eot aeeete ae aet hen eeta ao eooes  a toh henn taet t oeo hei  a  tooet t oha  ohott aee a a a tee e  oe  oee e  ota tee teo a et  e aaoen  hat he e eessis  hoa hoes heitthene  he haees  ae hte honee teo ha t he t oete heiss ho heietthe hei the ete  hteet henn taasse aoeesse te  ah  a oen tatanne th  haa t taetane  he

In [128]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i600_l512.ckpt
Far tood to take, and the
ence sand one with all a corsors it when an alowat attered
the prilies of this had brow the seeted of she was a to she sour husbars in the
carest of him.." Alexatdy her hears.

"I'r her
sardited him, was soming, then same one
had thimed of this still him. The could to her tray, and that he same on
the sert was and wint hear of
have and with all to to the stanst, he had a pruncess who house thought to the supered it
hand that the
prepansed him, which his had but, he was tood to the parstion the presentity, with said. Theye
some, and the persicess. His want to
sto had stond, and the sompition, and shisted a miling, bugh, and ther, as it she wist she came her was as the
rear his hears, and was astording of the soor at inseered him but to him.. The dreat had be suppire it the face, and all the chard of the strich with him to a more had been how a ment of her
said hose her heast all, the
word of a

In [129]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="venkat is a good kid")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i1200_l512.ckpt


NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/i1200_l512.ckpt
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2787, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-129-d7e3abdf30ff>", line 2, in <module>
    samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="venkat is a good kid")
  File "<ipython-input-124-8eb787ae9642>", line 4, in sample
    saver = tf.train.Saver()
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/venkata/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/i1200_l512.ckpt
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
